### ISSUE TITLE
Wrong file name -task

### ISSUE THREAD

**Issue by fri-it2** [perfsonar/ansible-role-perfsonar-maddash#2]
Hello
In directory tasks/ is file name: config_remotes.yml.
In playbook main.yml:

```
- name: add/delete remote mesh configurations that have a valid URL and state
  tags: [ 'ps::config' ]
  include_tasks: psconfig_remotes.yml
  with_items: "{{ perfsonar_maddash_remotes | default([]) }}"
  when:
    - item.url | default('') != ''
- item.state | default('present') in [ "absent", "present" ]
```
In playbook task/main.yml is included psconfig_remotes.yml. Is this bug?
Best regards,
Tadeja
